### ISSUE TITLE
Module Prototype to Validate viability

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/ansible-role-conjur#21]
As a first step to proving viability of a `Summon` like module, we should start with something very simple.  Our broad goal is to be provide the following functionality:

```yml
- hosts: webservers
  tasks:
    - name: ensure app Foo is running
      conjur_application:
        run:
          command: rails s
          args:
            chdir: /foo/app
        variables:
          - SECRET_KEY: /path/to/secret-key
          - SECRET_PASSWORD: /path/to/secret_password
```
Which would equate to running the following on the remote target:
```sh
$ cd /foo/app && SECRET_KEY=topsecretkey SECRET_PASSWORD=topsecretpassword rails s
```
The module we'll need to build will be: `conjur_application` (name may need to become more generic).  To start off, it should be able to execute an Ansible module (`command` in this case) and pass environment variables into it.

To begin, I propose we attempt to build the following:
```yml
- hosts: webservers
  tasks:
    - name: Output environment on remote instance with environment variables
      conjur_application:
        run:
          command: env
        variables:
          - SECRET_KEY: foo
```
The above example would result in the following being executed on the remote:
```sh
$ SECRET_KEY=foo env
``` 
The above should return a list of environment variables with `SECRET_KEY=foo`.

We'll also need to verify the command is being run on the remote target, not our host.

Once we've proven remote execution with environment variable injection, we'll be able to move onto retrieving these variables from Conjur using the underlying machine's identity.

Resources:
Ansible Developer Docs: https://docs.ansible.com/ansible/latest/dev_guide/index.html
If it's helpful (probably too low level), this is how we're doing it in Summon: https://github.com/cyberark/summon/blob/master/command/action.go
