### ISSUE TITLE
Module proxies requests to a provided process

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/ansible-role-conjur#33]
A module exists that allows secrets to be retrieved from Conjur using the host's identity to retrieve secrets from Conjur and pass them into the provided process.  An example of the interface is here:
```yml
  summon_conjur:
    variables:
      DB_USERNAME: !variable "{{app_environment}}/myapp/database/username"
      DB_PASSWORD: !variable "{{app_environment}}/myapp/database/password"
      STRIPE_API_KEY: !variable "{{app_environment}}/myapp/stripe/private_key"
      RAILS_ENV: production
    command: rackup -p 4567 --host 0.0.0.0 -D
```
Variables marked with `!variable` should be retrieved from Conjur.  Variables without `!variable` should be passed into the process as is.  In the above example, the argument `RAILS_ENV=production` should be passed directly to the provided process.  For example:

```sh
$ RAILS_ENV=production DB_USERNAME=db_staging_user ... rackup -p 4567 --host 0.0.0.0 -D
```

**Notes**
Most of this functionality, without the `!variable` target lookup, was implemented in the `ansiblefest` branch.  This functionality will require tests.
