### ISSUE TITLE
HTTPS connection with Conjur server

### ISSUE THREAD

**Issue by orenbm** [cyberark/ansible-role-conjur#8]
To enable an end use to connect to Conjur, they should be able to use the following three types of connections:

1. HTTP
2. HTTPS (with a publicly signed certificate)
3. HTTPS (with a self signed certificate)

The connection should be established with the Role, and used by the Module and the Lookup Plugin. Below are the expected setting for the Role:
1. HTTP
 ```yml
  roles:
    - role: ansible-role-conjur
      account: cucumber
      conjur_url: "http://conjur:3000"
      host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      host_name: "conjur_{{ ansible_hostname }}"
 ```
2. HTTPS (public)
```yml
  roles:
    - role: ansible-role-conjur
      account: cucumber
      conjur_url: "https://conjur:3000"
      host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      host_name: "conjur_{{ ansible_hostname }}"
 ```
3. HTTPS (self signed)
```yml
  roles:
    - role: ansible-role-conjur
      account: cucumber
      conjur_url: "https://conjur:3000"
      host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      host_name: "conjur_{{ ansible_hostname }}"
      ssl_certificate: "/path/to/conjur_cert"
 ```

Please not that the role parameters have been updated from the original to reflect the Readme.md examples.  

For this story to be complete, we need the following:
* Tests for at least example 1 & 3 (HTTP, HTTPS w/ self signed cert)
* All three examples documented in the Readme
* Module and Plugin Lookup using the connection established in the Role.

**Original Issue**
Some of our users will want to secure the connection with Conjur using HTTPS.  We need to insure that all three use cases (Role for Conjurizing, Lookup Plugin, and Module) support connecting over HTTPS with an optional CA Certificate.
